# Generated by Django 3.1.4 on 2020-12-17 04:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='bikes',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='closure_info',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='dogs',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='global_id',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='horses',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='measured_feet',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='segment_id',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='st_length',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='trail_type',
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TrailSegment',
            fields=[
                ('segment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=50, null=True)),
                ('bikes', models.BooleanField()),
                ('trail_type', models.CharField(max_length=50, null=True)),
                ('horses', models.BooleanField()),
                ('mileage', models.FloatField()),
                ('measured_feet', models.FloatField()),
                ('dogs', models.BooleanField()),
                ('st_length', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('closure_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trails.trailclosure')),
                ('parent_trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.trail')),
            ],
        ),
    ]
